version: "3.8"

services:
  app:
    image: app:0.2
    container_name: app_green
    environment:
      - "spring_profiles_active=blue"
      - S3_ACCESSKEY=${S3_ACCESSKEY}
      - S3_SECRETKEY=${S3_SECRETKEY}
      - HOST=${HOST}
      - JWT_SECRET=${JWT_SECRET}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_USER=${MONGODB_USER}
      - OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID}
      - OAUTH2_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CREDENTIAL_PATH=${CREDENTIAL_PATH}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - "8083:8080"
    volumes:
      - ./back-end:/app

    external_links:
      - dev-back_db_1:db
      - dev-back_mongodb_1:mongodb
      - dev-back_redis_1:redis
