version: "3.8"

services:
  frontend:
    build:
      # 어디에서 도커를 시작할 것인가
      context: ./front-end
      dockerfile: Dockerfile
    image: frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - app-network

  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    #
    volumes:
      # - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/data:/var/www/certbot

    ports:
      - "80:80"
      - "443:443"
    #
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot

    #  발급후에 커맨드 아래 재발급용 커맨드로 바꿔준다.
    # command: certonly --webroot --webroot-path=/var/www/certbot --email dongsu712@naver.com --agree-tos --no-eff-email -d rough-code.com
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/data:/var/www/certbot
      - ./data/certbot/logs:/var/log/letsencrypt

networks:
  app-network:
    driver: bridge
