version: "3.8"

services:
  db:
    image: mariadb:10.6.5
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ssafy306
      - MYSQL_DATABASE=alarm
      - MYSQL_USER=root
      - MYSQL_PASSWORD=ssafy306
    ports:
      - "3306:3306"
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:4.4.10
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ssafy306
      - MONGO_INITDB_ROOT_PASSWORD=ssafy306
  backend:
    build:
      context: ./back-end/roughcode
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./back-end:/app
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://k8a306.p.ssafy.io:3306/ssafy306
      - SPRING_DATASOURCE_USERNAME=ssafy306
      - SPRING_DATASOURCE_PASSWORD=ssafy306
      - REDIS_HOST=redis
  google-cloud-cli:
    image: google/cloud-sdk:latest
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/back-end/roughcode/credentials.json
    volumes:
      - /path/to/google-credentials.json:/back-end/roughcode/credentials.json
      - /path/to/.env:/.env
    entrypoint: /bin/bash

volumes:
  db-data:
  mongodb-data:
