version: "3.8"

services:
  sonarqube:
    image: sonarqube:lts
    depends_on:
      - sonardb
    container_name: sonarqube
    ports:
      - "8000:9000"
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    # networks:
    #   - sonarnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  sonardb:
    image: postgres:12
    container_name: postgres_sonar
    ports:
      - "5432:5432"
    # networks:
    #   - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

# networks:
#   sonarnet:
#     driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
