spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: ssafy306
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: false
      show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/RoughCode
    username: root
    password: ssafy306